import { memo, useState } from "react";
import type { Message } from "../../core/messages/types";
import { useDimensions } from "../context/dimensions";
import { useObfuscation } from "../context/obfuscation";
import { useTheme } from "../theme";
import { ShiningText, SpinningDots } from "./loaders";
import {
  getArgsPreview,
  getStableMessageKey,
  markdownToStyledText,
} from "./shared";

export type Subagent = {
  id: string;
  name: string;
  type: "attack-surface" | "pentest";
  target: string;
  messages: Message[];
  createdAt: Date;
  status: "pending" | "completed" | "failed" | "paused";
};

/**
 * Tool execution status.
 *
 * - `streaming` — tool name known; arguments still being generated by the model
 * - `pending`   — arguments complete; tool is executing
 * - `completed` — execution finished successfully
 * - `error`     — execution finished with an error
 */
export type ToolStatus = "streaming" | "pending" | "completed" | "error";

/**
 * Per-subagent log entry for tools that spawn child agents.
 */
export type SubagentLogEntry = {
  name?: string;
  status: "pending" | "completed" | "failed";
  logs: string[];
};

/**
 * Workflow phase identifier.
 */
export type WorkflowPhase =
  | "discovery"
  | "pentesting"
  | "reporting"
  | "complete";

/**
 * All state for the pentest workflow rendered by PentestWorkflowDisplay.
 * Lives on the `run_pentest_workflow` tool message.
 */
export type WorkflowData = {
  currentPhase: WorkflowPhase;
  discovery: {
    label: string;
    status: "pending" | "complete";
    logs: string[];
    targets?: { target: string; objectives: string[] }[];
    cached?: boolean;
  };
  pentesting: {
    label: string;
    status: "idle" | "pending" | "complete";
    subagents: Record<string, SubagentLogEntry>;
  };
  reporting: {
    label: string;
    status: "idle" | "pending" | "complete";
    findingsCount?: number;
    findingsBySeverity?: Record<string, number>;
    reportPath?: string;
  };
};

/**
 * Display message type - flexible type for UI display.
 *
 * For tool messages: toolCallId, toolName, args, and status are required.
 * For text messages: only role, content, and createdAt are required.
 *
 * Use isToolMessage() type guard for safe narrowing to tool messages.
 */
export type DisplayMessage = {
  role: "user" | "assistant" | "system" | "tool";
  content: string | unknown[];
  createdAt: Date;
  // Tool-specific fields (present when role === "tool")
  toolCallId?: string;
  toolName?: string;
  args?: Record<string, unknown>;
  result?: unknown;
  status?: ToolStatus;
  logs?: string[];
  subagentLogs?: Record<string, SubagentLogEntry>;
  // Pentest workflow display (present for run_pentest_workflow tool)
  workflowData?: WorkflowData;
  // Plan review display (present when isPlanReview === true)
  isPlanReview?: boolean;
  planContent?: string;
};

function getStableKey(
  item: DisplayMessage | Subagent,
  contextId: string = "root",
): string {
  // Subagents have their own unique ID
  if ("messages" in item) {
    return `subagent-${item.id}`;
  }
  // Use shared utility for display messages
  return getStableMessageKey(item, contextId);
}

interface AgentDisplayProps {
  messages: DisplayMessage[];
  isStreaming?: boolean;
  children?: React.ReactNode;
  subagents?: Subagent[];
  paddingLeft?: number;
  paddingRight?: number;
  contextId?: string; // Used to ensure unique keys across nested displays
  focused?: boolean; // Controls whether this scrollbox responds to scroll events
}

function AgentDisplay({
  messages,
  isStreaming = false,
  children,
  subagents,
  paddingLeft = 8,
  paddingRight = 8,
  contextId = "root",
  focused = true,
}: AgentDisplayProps) {
  const { colors } = useTheme();
  // Sort messages and subagents by creation time
  // Don't use useMemo to ensure we always have fresh data during rapid updates
  const messagesAndSubagents = [...messages, ...(subagents ?? [])].sort(
    (a, b) => a.createdAt.getTime() - b.createdAt.getTime(),
  );

  return (
    <scrollbox
      style={{
        rootOptions: {
          width: "100%",
          maxWidth: "100%",
          flexGrow: 1,
          flexShrink: 1,
        },
        contentOptions: {
          paddingLeft: paddingLeft,
          paddingRight: paddingRight,
          gap: 1,
          flexDirection: "column",
        },
        scrollbarOptions: {
          trackOptions: {
            foregroundColor: colors.textMuted,
            backgroundColor: colors.backgroundElement,
          },
        },
      }}
      stickyScroll={true}
      stickyStart="bottom"
      focused={focused}
      onMouseScroll={
        !focused
          ? (event: { stopPropagation: () => void }) => {
              // Stop scroll events from propagating to parent scrollbox
              event.stopPropagation();
            }
          : undefined
      }
    >
      {messagesAndSubagents.map((item) => {
        // Get stable unique key for this item, using contextId to prevent collisions
        const itemKey = getStableKey(item, contextId);

        if ("messages" in item) {
          return (
            <box key={itemKey}>
              <SubAgentDisplay subagent={item} />
            </box>
          );
        } else {
          return (
            <box key={itemKey}>
              <AgentMessage message={item} />
            </box>
          );
        }
      })}

      {isStreaming && (
        <box flexDirection="row" alignItems="center">
          <SpinningDots label="Thinking..." fg={colors.primary} />
        </box>
      )}

      {children}
    </scrollbox>
  );
}

const SubAgentDisplay = memo(function SubAgentDisplay({
  subagent,
}: {
  subagent: Subagent;
}) {
  const { colors } = useTheme();
  // Subscribe so memoised render bypasses cached output on /obfuscate toggle.
  useObfuscation();
  const [open, setOpen] = useState(false);

  return (
    <box
      height={open ? 40 : "auto"}
      onMouseDown={() => setOpen(!open)}
      width="100%"
      border={true}
      borderColor={colors.primary}
      backgroundColor={colors.background}
    >
      <box flexDirection="row" alignItems="center" gap={1}>
        {subagent.status === "pending" && (
          <SpinningDots label={subagent.name} fg={colors.primary} />
        )}
        {subagent.status === "completed" && (
          <text fg={colors.primary}> ✓ {subagent.name}</text>
        )}
        {subagent.status === "failed" && (
          <text fg={colors.error}>✗ {subagent.name}</text>
        )}
        {subagent.status === "paused" && (
          <text fg={colors.tierRisky}>⏸ {subagent.name}</text>
        )}
        <text fg={colors.textMuted}>{open ? "▼" : "▶"}</text>
      </box>
      {open && (
        <AgentDisplay
          paddingLeft={2}
          paddingRight={2}
          messages={subagent.messages}
          contextId={subagent.id}
          focused={false}
        />
      )}
    </box>
  );
});

const AgentMessage = memo(function AgentMessage({
  message,
}: {
  message: DisplayMessage;
}) {
  const { colors } = useTheme();
  const dimensions = useDimensions();
  // Subscribe so memoised render bypasses cached output on /obfuscate toggle.
  useObfuscation();
  let content = "";

  if (typeof message.content === "string") {
    content = message.content;
  } else if (Array.isArray(message.content)) {
    // Handle array of content parts
    content = message.content
      .map((part: unknown) => {
        if (typeof part === "string") return part;
        if (
          typeof part === "object" &&
          part !== null &&
          "type" in part &&
          (part as Record<string, unknown>).type === "text"
        )
          return (part as Record<string, unknown>).text as string;
        return JSON.stringify(part);
      })
      .join("");
  } else {
    content = JSON.stringify(message.content, null, 2);
  }

  // For completed tool messages, extract the message field from the result if present
  if (
    message.role === "tool" &&
    message.status === "completed" &&
    message.result &&
    typeof message.result === "object" &&
    "message" in message.result &&
    typeof (message.result as Record<string, unknown>).message === "string"
  ) {
    content = (message.result as Record<string, unknown>).message as string;
  }

  // Render markdown for assistant messages (markdown pipeline obfuscates
  // internally). Plain-text branches flow into `<text>` children, where
  // the central TextNodeRenderable patch handles redaction.
  const displayContent =
    message.role === "assistant"
      ? markdownToStyledText(content, colors)
      : content;

  const isPendingTool =
    message.role === "tool" &&
    (message.status === "pending" || message.status === "streaming");
  const isCompletedTool =
    message.role === "tool" && message.status === "completed";
  const isErrorTool = message.role === "tool" && message.status === "error";

  // Get args preview for tool messages
  const argsPreview =
    message.role === "tool" && message.args
      ? getArgsPreview(message.toolName || "", message.args, 80)
      : "";

  // Get streaming logs for pending tools
  const streamingLogs = message.logs || [];

  return (
    <box
      flexDirection="column"
      width="100%"
      gap={1}
      alignItems={message.role === "user" ? "flex-end" : "flex-start"}
    >
      <box flexDirection="row" gap={0}>
        {message.role === "assistant" && (
          <box
            width={0}
            borderStyle="heavy"
            border={["right"]}
            borderColor={colors.borderSubtle}
          />
        )}
        <box
          maxWidth={dimensions.width - 20}
          padding={message.role !== "tool" ? 1 : 0}
          backgroundColor={
            message.role !== "tool" ? colors.backgroundElement : undefined
          }
          flexDirection="column"
        >
          {isPendingTool ? (
            <>
              <ShiningText text={content} fg={colors.warning} />
              {/* Args preview for pending tools */}
              {argsPreview && (
                <text fg={colors.textMuted} content={`  ${argsPreview}`} />
              )}
              {/* Streaming logs for pending tools */}
              {streamingLogs.length > 0 && (
                <box flexDirection="column" marginTop={0} paddingLeft={2}>
                  {streamingLogs.slice(-3).map((log, idx) => {
                    const trimmed =
                      log.length > 100 ? `${log.slice(0, 100)}…` : log;
                    const offset = Math.max(0, streamingLogs.length - 3) + idx;
                    return (
                      <text
                        key={`${message.toolCallId}-log-${offset}`}
                        fg={colors.textMuted}
                      >
                        {trimmed}
                      </text>
                    );
                  })}
                </box>
              )}
            </>
          ) : (
            <>
              {/* Completed/error tool indicator */}
              {message.role === "tool" && (
                <box flexDirection="row" gap={1}>
                  <text fg={isErrorTool ? colors.error : colors.primary}>
                    {isErrorTool ? "✗" : "✓"}
                  </text>
                  <text fg={colors.text} content={displayContent} />
                </box>
              )}
              {message.role !== "tool" && (
                <text fg={colors.text} content={displayContent} />
              )}
              {/* Args preview for completed tools */}
              {message.role === "tool" && argsPreview && (
                <text fg={colors.textMuted} content={`  ${argsPreview}`} />
              )}
            </>
          )}
        </box>
        {message.role === "user" && (
          <box
            width={0}
            borderStyle="heavy"
            border={["left"]}
            borderColor={colors.borderSubtle}
          />
        )}
      </box>
      <ToolDetails message={message} />
    </box>
  );
});

function ToolDetails({ message }: { message: DisplayMessage }) {
  const { colors } = useTheme();
  const [showArgs, setShowArgs] = useState(false);
  const [showResult, setShowResult] = useState(false);

  if (message.role !== "tool") {
    return null;
  }

  const hasArgs = "args" in message && message.args;
  const hasResult = "result" in message && message.result !== undefined;

  if (!hasArgs && !hasResult) {
    return null;
  }

  // Format result for display (truncate if too long). Redaction is
  // handled by the central TextNodeRenderable patch when this string
  // hits a `<text>` child.
  const formatResult = (result: unknown): string => {
    let str: string;
    try {
      str = JSON.stringify(result, null, 2);
    } catch {
      str = String(result);
    }
    const truncated =
      str.length > 2000 ? `${str.substring(0, 2000)}\n... (truncated)` : str;
    return truncated;
  };

  return (
    <box flexDirection="column" gap={1}>
      {hasArgs && (
        <box
          onMouseDown={(e) => {
            e.stopPropagation();
            setShowArgs(!showArgs);
          }}
        >
          <box flexDirection="row" alignItems="center" gap={1}>
            <text fg={colors.textMuted}>
              {showArgs ? "▼ Hide args" : "▶ Show args"}
            </text>
          </box>
          {showArgs && (
            <text fg={colors.text}>
              {JSON.stringify(message.args, null, 2)}
            </text>
          )}
        </box>
      )}
      {hasResult && (
        <box
          onMouseDown={(e) => {
            e.stopPropagation();
            setShowResult(!showResult);
          }}
        >
          <box flexDirection="row" alignItems="center" gap={1}>
            <text fg={colors.success}>
              {showResult ? "▼ Hide output" : "▶ Show output"}
            </text>
          </box>
          {showResult && (
            <text fg={colors.success}>{formatResult(message.result)}</text>
          )}
        </box>
      )}
    </box>
  );
}
